Issues Resolved
ToxicBot-Discord/ToxicBot pull request #22
Opened 2020-10-14 08:57 UTC by jigyasudhingra

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes (if any) #(issue_no) 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/Sid200026/ToxicBot/blob/master/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

2020-10-14 09:06 UTC, Sid200026 commented
Please resolve the merge conflict

2020-10-14 09:32 UTC, jigyasudhingra commented
I resolved the merge conflict.

2020-10-14 14:08 UTC, Sid200026 requested changes
I have requested some changes @jigyasudhingra

2020-10-14 14:08 UTC, Sid200026 commented on ToxicBot/commands/listener.py
>      # When the bot is added to a server
You added the method in the wrong spot. This comment line should be before on_guild_join method.

2020-10-14 14:08 UTC, Sid200026 commented on ToxicBot/commands/listener.py
> +        if channel is not None:
Many channels do not have a dedicated system channel. What you could do is if a system channel does not exist, then send a private dm to the user

2020-10-14 14:08 UTC, Sid200026 commented on ToxicBot/commands/listener.py
> +            await channel.send('Welcome {0.mention}.'.format(member))
The current message does not contain any information about the bot. Suppose you join a server and you find ToxicBot messaging you Welcome @jigyasudhingra . You wouldn't know anything about what it does, what commands it can run etc. So you need to provide a more informative message to the user instead of a simple welcome.

2020-10-15 15:40 UTC, Sid200026 commented
Just add the changes you made in the other pull request here and we are good to go.

2020-10-15 15:41 UTC, Sid200026 commented on ToxicBot/commands/listener.py
> +        if system_channel is None:
should be channel instead of system_channel

2020-10-15 18:17 UTC, Sid200026 commented
The changes made in constant/messages.py isn't present in this PR

2020-10-15 18:19 UTC, jigyasudhingra commented
> 
> 
> The changes made in constant/messages.py isn't present in this PR

I made this change just now, you can check it now.

2020-10-15 18:38 UTC, Sid200026 commented
Everything looks good to me. Thank you for your contribution. All the best.

2020-10-15 18:38 UTC, Sid200026 approved these changes

2020-10-15 18:38 UTC, merged

2020-10-15 19:07 UTC, jigyasudhingra commented
> 
> 
> Everything looks good to me. Thank you for your contribution. All the best.

Thank you so much and all the best to you too.

2020-10-16 13:55 UTC, Sid200026 commented on ToxicBot/commands/listener.py
> +
There is an bracket missing here. Submitting PRs without testing them causes a lot of problem in the future. Please be careful next time @jigyasudhingra

2020-10-16 14:03 UTC, Sid200026 commented
Sorry but this PR does not work. I'll have to revert it.